### PR TITLE
Tidied up RNG a bit (Closes #111)

### LINKED ISSUE #111: Random Numbers Overhaul
There are currently quite a few different methods of generating random numbers, and quite a few different functions for doing it spread all over the code.

It would probably be a *lot* easier if the functions were kept in a single place, and all the different uses of these random number were changed to use these functions only where possible

### PR DESCRIPTION
**Pull request by ExultantMonkey**

### CODE REVIEW

**Comment by KennethGF** [comment]
thanks

**Comment by ExultantMonkey** [comment]
Are you sure that you meant to close it instead of merging it?

**Comment by bote-reginald** [comment]
good point - why was it closed ?

**Comment by bote-reginald** [comment]
ok - have read it

**Pull request merged**
