### PR TITLE
Adding the health value in Events

### PR DESCRIPTION
**Pull request by KennethGF**
Want to see what you think of this before I do any more with it.

### CODE REVIEW

**Comment by KennethGF** [comment]
Regarding growth rate dropping if health goes bad; In Colony.cs you rewrote the interaction to be" line 299  =  var baseGrowthRate = ((decimal)System.GetGrowthRate(Inhabitants) * (decimal)_health.PercentFilled) * 100;
Is there a good or better way here to make a health value, that is less than the base value of 80, result in a greater or lesser decrease in baseGrowthRate?

**Comment by ExultantMonkey** [comment]
I shall implement it later on if you want? What should I set the baseline for population going down. 25%, 50? 50 would be the easiest to do I thinkOn 7 Sep 2018 12:44, Kenneth Of Borg <notifications@github.com> wrote:Regarding growth rate dropping if health goes bad; In Colony.cs you rewrote the interaction to be" line 299  =  var baseGrowthRate = ((decimal)System.GetGrowthRate(Inhabitants) * (decimal)_health.PercentFilled) * 100;
Is there a good or better way here to make a health value, that is less than the base value of 80, result in a greater or lesser decrease in baseGrowthRate?

**Comment by ExultantMonkey** [comment]
Quick tinker around in Excel returns this for 50% - baseGrowthRate*((-0.5+populationHealth)*2)

So for a base growth rate of 3.4%, a health of 100% gives 3.4%, 50% gives 0%, and 0% gives -3.4%

**Comment by KennethGF** [comment]
Thanks,  will look further after work.

ken

**Pull request merged**
